sudo: false
cache: bundler
language: ruby
rvm:
  - 2.1
  - 2.1.6
  - 2.2
  - 2.3.0
  - ruby-head
  - jruby-19mode
  - jruby-9.0.1.0
  - rbx-3
env:
  # this doesn't do anything for MRI or RBX, but it doesn't hurt them either
  # for JRuby, it enables us to get more accurate coverage data
  - JRUBY_OPTS="--debug"
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-3
    - rvm: jruby-19mode
    - rvm: jruby-9.0.1.0
    - rvm: 1.9.3
    - rvm: 2.0.0
  fast_finish: true
before_install: gem update --remote bundler
install:
  - bundle install --retry=3
script:
  - bundle exec rspec
addons:
  code_climate:
    repo_token: 9bc6cf480824676f6f459544eb93d3ad09b4a69e9b42c57c5e657748c38b779a
